#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("iOSConsortium.Droid.Resource", IsApplication=true)]

namespace iOSConsortium.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int civ_border_color = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int civ_border_overlay = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int civ_border_width = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int civ_fill_color = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int colorAccent = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int colorPrimary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int colorPrimaryDark = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_horizontal_margin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int activity_vertical_margin = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int getSpeakersButton = 2131230720;
			
			// aapt resource value: 0x7f080004
			public const int imageView = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int linearLayout1 = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int linearLayout2 = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int mainText = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int progressBar = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int speakersListView = 2131230721;
			
			// aapt resource value: 0x7f080007
			public const int subText = 2131230727;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int SpeakersView = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CircleImageView = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int CircleImageView_civ_border_color = 1;
			
			// aapt resource value: 2
			public const int CircleImageView_civ_border_overlay = 2;
			
			// aapt resource value: 0
			public const int CircleImageView_civ_border_width = 0;
			
			// aapt resource value: 3
			public const int CircleImageView_civ_fill_color = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
